---
    apiVersion: v1
    kind: Service
    metadata:
      name: hangman-api-service
    spec:
      ports:
        - port: 9905
          targetPort: 9905
          name: http
          protocol: TCP
      selector:
        app: hangman-api