---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hangman-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hangman-api
      template:
        metadata:
          labels:
            app: hangman-api
        spec:
          containers:
          - name: backend
            image: gcr.io/sylvan-epoch-274407/hangman-api
            ports:
              - containerPort: 9905