---
    apiVersion: v1
    kind: Service
    metadata:
      name: backend-service
    spec:
      ports:
        - port: 80
          targetPort: 8080
          name: http
          protocol: TCP
      selector:
        app: backend