---
    apiVersion: v1
    kind: Service
    metadata:
      name: hangman-ui-service
      annotations:
        getambassador.io/config: |
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: hangman-ui-mapping
          prefix: /
          service: hangman-ui-service
          host_rewrite: hangman-ui-service
    spec:
      ports:
        - port: 80
          targetPort: 9000
          name: http
          protocol: TCP
      selector:
        app: hangman-deployment-ui